##
# MVdWPlaceholderAPI
#
# @copyright Maxim Van de Wynckel
##

name: MVdWPlaceholderAPI
version: 3.1.1
description: Placeholder API for MVdW Software plugins
author: Maximvdw
website: https://www.mvdw-software.com/
main: be.maximvdw.placeholderapi.PlaceholderAPI